import createFeatureLayer from "../utils/layer-utils";
import { LayerIds } from "../utils/LayerIds";
function SearchLayer({ WFSLayer }) {
  return [
    {
      layer: createFeatureLayer(WFSLayer, LayerIds.DistrictBoundarySearch,'District_Boundary', 'District Boundary', false),
      searchFields: ['district', 'division'],
      suggestionTemplate: 'Layer:District Boundary >> Division:{division} | District:{district}',
      exactMatch: false,
      outFields: ['*'],
      name:'District',
      placeholder: 'Search for District',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    },
    {
      layer: createFeatureLayer(WFSLayer, LayerIds.TalukaBoundarySearch,'Taluka_Boundary' ,'Taluka Boundary', false),
      searchFields: ['dtname11', 'thname11'],
      suggestionTemplate: 'Layer:Taluka Boundary >> District:{dtname11} | Taluka:{thname11}',
      exactMatch: false,
      outFields: ['*'],
      name:'Taluka',
      placeholder: 'Search for Taluka',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    },
    {
      layer: createFeatureLayer(WFSLayer, LayerIds.VillageBoundarySearch,'Village_Boundary', 'Village Boundary', false),
      searchFields: ['d_name', 't_name', 'name'],
      suggestionTemplate: 'Layer:Village Boundary >> District:{d_name} | Taluka:{t_name} | Village:{name}',
      exactMatch: false,
      outFields: ['*'],
      name:'Village',
      placeholder: 'Search for Village',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    },
    {
      layer: createFeatureLayer(WFSLayer, LayerIds.AssemblyConstituenciesSearch,'Assembly_Constituencies', 'Assembly Constituency', false),
      searchFields: ['dist_name', 'name'],
      suggestionTemplate: 'Layer:Assembly Constituency >> District:{dist_name} | Name:{name}',
      exactMatch: false,
      outFields: ['*'],
      name:'Assembly Constituency',
      placeholder: 'Search for Assembly Constituency',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    },
    {
      layer: createFeatureLayer(WFSLayer, LayerIds.ParliamentaryConstituencySearch,'Parliamentary_Constituency', 'Parliamentary Constituency', false),
      searchFields: ['dist_name', 'name', 'pc_name'],
      suggestionTemplate: 'Layer:Parliamentary Constituency >> District:{dist_name} | Name:{name} | PC Name:{pc_name}',
      exactMatch: false,
      outFields: ['*'],
      name:'Parliamentary Constituency',
      placeholder: 'Search for Parliamentary Constituency',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    },
    {
      layer: createFeatureLayer(WFSLayer, LayerIds.RiverandWaterbodaySearch,'Riverand_Waterboday', 'River and Waterboday', false),
      searchFields: ['discr', 'name'],
      suggestionTemplate: 'Layer:River and Waterboday >> Discription:{discr} | Name:{name}',
      exactMatch: false,
      outFields: ['*'],
      name:'River and Waterboday',
      placeholder: 'Search for River and Waterboday',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    },
    {
      layer: createFeatureLayer(WFSLayer, LayerIds.HospitalLocationSearch,'Hospital_Location', 'Hospital Locations', false),
      searchFields: ['dist_namename', 'taluka'],
      suggestionTemplate: 'Layer:Hospital Location >> Name:{name} | Taluka:{taluka}',
      exactMatch: false,
      outFields: ['*'],
      name:'Hospital Location',
      placeholder: 'Search for Hospital Location',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    },
    {
      layer: createFeatureLayer(WFSLayer, LayerIds.VeterinaryHospitalSearch,'Veterinary_Hospital', 'Veterinary Hospitals', false),
      searchFields: ['village', 'veterinary'],
      suggestionTemplate: 'Layer: Veterinary Hospital >> Village:{village} | Veterinary:{veterinary}',
      exactMatch: false,
      outFields: ['*'],
      name:'Veterinary Hospital',
      placeholder: 'Search for Veterinary Hospital',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    }, {
      layer: createFeatureLayer(WFSLayer, LayerIds.PoliceStationSearch,'police_station', 'Police stations', false),
      searchFields: ['name', 'taluka'],
      suggestionTemplate: 'Layer: Police station >> Name:{dist_name} | Taluka:{taluka}',
      exactMatch: false,
      outFields: ['*'],
      name:'Police station',
      placeholder: 'Search for Police station',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    }, {
      layer: createFeatureLayer(WFSLayer, LayerIds.MonumentLocationSearch,'Monument_Location', 'Monument Locations', false),
      searchFields: ['place', 'name', 'taluka', 'district'],
      suggestionTemplate: 'Layer: Monument Location >>  Name:{name} | Place:{place} | District:{dist_name} | Taluka:{taluka}',
      exactMatch: false,
      outFields: ['*'],
      name:'Monument Location',
      placeholder: 'Search for Monument Location',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    }, {
      layer: createFeatureLayer(WFSLayer, 'Fort', 'Forts', false),
      searchFields: ['name'],
      suggestionTemplate: 'Layer:Fort >> Name:{name}',
      exactMatch: false,
      outFields: ['*'],
      name:'Fort',
      placeholder: 'Search for Fort',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    }, {
      layer: createFeatureLayer(WFSLayer,LayerIds.GovtadminDepartSearch, 'govt_admin_depart', 'Admin Departments', false),
      searchFields: ['taluka', 'name'],
      suggestionTemplate: 'Layer: Admin Department >> Taluka:{taluka} | Name:{name}',
      exactMatch: false,
      outFields: ['*'],
      name:'Admin Department',
      placeholder: 'Search for Admin Department',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    },
    {
      layer: createFeatureLayer(WFSLayer, LayerIds.SchoolLocationSearch,'school_location', 'School Locations', false),
      searchFields: ['districtna', 'block_name', 'schoolname'],
      suggestionTemplate: 'Layer: School Location >> District:{districtna} | Block Name:{block_name} | School Name:{schoolname}',
      exactMatch: false,
      outFields: ['*'],
      name:'School Location',
      placeholder: 'Search for School Location',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    },
    {
      layer: createFeatureLayer(WFSLayer, LayerIds.TransportationSearch,'transportation', 'Transportations', false),
      searchFields: ['taluka', 'name'],
      suggestionTemplate: 'Layer: Transportation >> Taluka:{taluka} | Name:{name}',
      exactMatch: false,
      outFields: ['*'],
      name:'Transportation',
      placeholder: 'Search for Transportation',
      maxResults: 10,
      localSearchDisabled: false,
      zoomScale: 500000,
    }
  ];
}
export default SearchLayer;