export const LayerIds=Object.freeze({
    adminLayerId:"adminLayerIds",
    DistrictBoundarySearch:"DistrictBoundarySearch",
    TalukaBoundarySearch:"TalukaBoundarySearch",
    VillageBoundarySearch:"VillageBoundarySearch",
    AssemblyConstituenciesSearch:"AssemblyConstituenciesSearch",
    ParliamentaryConstituencySearch:"ParliamentaryConstituencySearch",
    RiverandWaterbodaySearch:"RiverandWaterbodaySearch",
    HospitalLocationSearch:"HospitalLocationSearch",
    VeterinaryHospitalSearch:"VeterinaryHospitalSearch",
    PoliceStationSearch:"PoliceStationSearch",
    MonumentLocationSearch:"MonumentLocationSearch",
    GovtadminDepartSearch:"GovtadminDepartSearch",
    SchoolLocationSearch:"SchoolLocationSearch",
    TransportationSearch:"TransportationSearch",
    transportation:"transportation",
    schoolLocation:'school_location',
    govtAdminDepart:'govt_admin_depart',
    fort:'Fort',
    settlementPoint:'Settlement_Point',
    monumentLocation:'Monument_Location',
    policestation:'police_station',
    veterinaryHospital:'Veterinary_Hospital',
    hospitalLocation:'Hospital_Location',
    roadBlackSpot:'road_black_spot',
    railTrack:'Rail_Track',
    road: 'Road',
    contour: 'Contour',
    riverandWaterboday: 'Riverand_Waterboday',
    parliamentaryConstituency: 'Parliamentary_Constituency',
    assemblyConstituencies: 'Assembly_Constituencies',
    villageBoundary: 'Village_Boundary',
    talukaBoundary: 'Taluka_Boundary',
    districtBoundary: 'District_Boundary',
    talukaBoundaryZoom:'TalukaBoundaryZoom'
})